import type { ComponentType } from "react";

import {
  ArrowRightIcon,
  SwatchBookIcon,
  StarIcon,
  ShieldCheckIcon,
  CpuIcon,
  BarChart2Icon,
  ZapIcon,
} from "lucide-react";

import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";

import { cn } from "@/lib/utils";
import { FeatureCard } from "./FeatureCard";

type FeaturesType = {
  icon: ComponentType;
  title: string;
  description: string;
  cardBorderColor: string;
  avatarTextColor: string;
  avatarBgColor: string;
}[];

const featuresList: FeaturesType = [
  {
    icon: SwatchBookIcon,
    title: "Detailed Stats",
    description:
      "Track your commits, pull requests, repositories, and contributions over time. Understand your productivity trends with clear visualizations.",
    cardBorderColor: "border-primary/40 hover:border-primary",
    avatarTextColor: "text-primary",
    avatarBgColor: "bg-primary/10",
  },
  {
    icon: CpuIcon,
    title: "Top Technologies",
    description:
      "Analyze your main programming languages and frameworks. See which tech you use most and how your skillset evolves.",
    cardBorderColor: "border-green-600/40 hover:border-green-600",
    avatarTextColor: "text-green-600",
    avatarBgColor: "bg-green-600/10",
  },
  {
    icon: ZapIcon,
    title: "AI Recommendations",
    description:
      "Get personalized insights and tips generated by AI to improve your coding skills and workflow efficiency.",
    cardBorderColor: "border-amber-600/40 hover:border-amber-600",
    avatarTextColor: "text-amber-600",
    avatarBgColor: "bg-amber-600/10",
  },
  {
    icon: BarChart2Icon,
    title: "Progress Tracking",
    description:
      "Visualize your growth over time with charts and stats. Know where you excel and what needs improvement.",
    cardBorderColor: "border-destructive/40 hover:border-destructive",
    avatarTextColor: "text-destructive",
    avatarBgColor: "bg-destructive/10",
  },
  {
    icon: StarIcon,
    title: "Achievements & Highlights",
    description:
      "See your top repositories, most impactful pull requests, and key milestones to celebrate your progress.",
    cardBorderColor: "border-sky-600/40 hover:border-sky-600",
    avatarTextColor: "text-sky-600",
    avatarBgColor: "bg-sky-600/10",
  },
  {
    icon: ShieldCheckIcon,
    title: "Secure & Private",
    description:
      "Your GitHub data stays secure. We only read public info with OAuth and never store sensitive credentials.",
    cardBorderColor: "border-primary/40 hover:border-primary",
    avatarTextColor: "text-primary",
    avatarBgColor: "bg-primary/10",
  },
];

export default function Features() {
  return (
    <section className="py-8 sm:py-16 lg:py-24 px-4 sm:px-6 lg:px-8">
      <div className="mx-auto">
        {/* Header */}
        <div className="mb-12 space-y-4 sm:mb-16 lg:mb-24">
          <h2 className="text-2xl font-semibold md:text-3xl lg:text-4xl">
            Discover your Dev Insights
          </h2>
          <p className="text-muted-foreground text-xl">
            Explore key features designed to help you track your progress,
            understand your skills, and improve with AI-powered recommendations.
          </p>
        </div>

        <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
          {featuresList.map((feature, index) => (
            <FeatureCard key={index} {...feature} />
          ))}
        </div>
      </div>
    </section>
  );
}
